apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-pod
    spec:
      containers:
        - name: myapp-pod
          image: "grzegorzskorupa/myapp:10.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # NEW SECTION - START
          livenessProbe:
            failureThreshold: 2
            timeoutSeconds: 4
            periodSeconds: 20
            httpGet:
              path: /alive
              port: 80
          readinessProbe:
            timeoutSeconds: 2
            periodSeconds: 20
            httpGet:
              path: /ready
              port: 80
          # NEW SECTION - END