apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-pod
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-pod
    spec:
      containers:
        - name: myapp-pod
          image: "grzegorzskorupa/myapp:1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # NEW SECTION - START
          env:
            - name: VAR_FROM_POD_DEFINITION
              value: "yupi"
            - name: VAR_FROM_CONFIG_MAP
              valueFrom:
                configMapKeyRef:
                  name: myapp-config-map
                  key: var_from_config_map
            - name: VAR_FROM_SECRET
              valueFrom:
                secretKeyRef:
                  name: myapp-secrets
                  key: var_from_secret
          # NEW SECTION - END
          livenessProbe:
            failureThreshold: 3
            timeoutSeconds: 4
            periodSeconds: 20
            httpGet:
              path: /alive
              port: 80
          readinessProbe:
            timeoutSeconds: 2
            periodSeconds: 20
            httpGet:
              path: /ready
              port: 80
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi