apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-role-binding
  namespace: rbac
subjects:
  - kind: ServiceAccount
    name: inception-creator
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io