apiVersion: v2
name: myapp
description: A Helm chart for Kubernetes to setup ML Forecasting API Service
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: "redis"
    version: "16.12.2"
    repository: "https://charts.bitnami.com/bitnami"
